disabled_rules:
#- force_try
#- force_cast

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods

identifier_name:
  warning: 1
  error: 1
identifier_name:
  warning: 1
  error: 1
